### ISSUE TITLE
Suggestion on error handling

### ISSUE THREAD

**Issue by dbz78** [ANSSI-FR/ADTimeline#1]
Hello, thanks for this script!

From my integration engineer perspective, there are some enhancements you could consider on error handling.
I join my proposal for the starting section.

Since I am really bad in using GitHub, I attach my file rather than pasting code here. Display is awful. 

My excerpt code is tested on my Win10 Enterprise/PS 5.1.17134.407

I go on reviewing your code.

DBZ78

**Comment by dbz78** [comment]
[ADTimeline_error-handling-proposal.txt](https://github.com/ANSSI-FR/ADTimeline/files/2807038/ADTimeline_error-handling-proposal.txt)

**Comment by dbz78** [comment]
Actually, I am really newbie with this GitHub thing!
I closed my previous comment instead of editing it.

[ADTimeline_error-handling-proposal.txt](https://github.com/ANSSI-FR/ADTimeline/files/2807040/ADTimeline_error-handling-proposal.txt)

**Comment by ldap389** [comment]
Reopening the issue.
Good point, I will test it and integrate it in next release.

**Comment by ldap389** [comment]
Suggestions commited.
