### ISSUE TITLE
Cannot contact server in offline mode

### ISSUE THREAD

**Issue by fastlorenzo** [ANSSI-FR/ADTimeline#10]
Hi, 

I have the following issue when running the tool in offline mode:

![image](https://user-images.githubusercontent.com/768639/99908912-aa3a1c00-2ce5-11eb-8dc2-f02e05e6a82f.png)

I've correctly used `dsamain.exe` and can manually browse using `ADSIEdit`:

![image](https://user-images.githubusercontent.com/768639/99908869-75c66000-2ce5-11eb-95c4-b34ceabe4422.png)

Any idea on what is possibly wrong there? 

The NTDS dump is coming from a Windows 2008 R2 SP1, and I've made a clean install + added the necessary requirements (AD LDS services and RSAT AD LDS).

**Comment by ldap389** [comment]
Hello,

Did you ensure the Active Directory Web Service (ADWS) is running?
If yes, please try to restart it after mounting the database and run the ADTimeline script.

Regards

**Comment by fastlorenzo** [comment]
thanks, looks like that did the trick 👍 

Thanks for the great tool btw!

**Comment by ant1** [comment]
> Did you ensure the Active Directory Web Service (ADWS) is running?
> If yes, please try to restart it after mounting the database and run the ADTimeline script.

Hello,

Do you mean that in offline mode,  you have to use a Windows Server and that a Windows 10 workstation will not be ok?

**Comment by ldap389** [comment]
> 
> 
> > Did you ensure the Active Directory Web Service (ADWS) is running?
> > If yes, please try to restart it after mounting the database and run the ADTimeline script.
> 
> Hello,
> 
> Do you mean that in offline mode, you have to use a Windows Server and that a Windows 10 workstation will not be ok?

Hello ant1

Yes you need a Windows Server edition with the following roles/features: ADLDS + RSAT-AD-Tools installed to use offline mode. It does not work on Windows 10 workstation.

**Comment by rwiesbach** [comment]
> Yes you need a Windows Server edition with the following roles/features: ADLDS + RSAT-AD-Tools installed to use offline mode. It does not work on Windows 10 workstation.

This should really be mentioned directly in the Readme. The Readme mentions Windows NT 6.1, which means Win 7, Win Server 2008 R2 and above.

**Comment by ldap389** [comment]
Hello @rwiesbach 
Readme was updated to mention Windows Server for offline mode analysis.

**Comment by rwiesbach** [comment]
Excellent reaction time, thank you!
