### ISSUE TITLE
Fundamental questions about replication metadata and ADTimeline

### ISSUE THREAD

**Issue by rwiesbach** [ANSSI-FR/ADTimeline#13]
I hope this a the right place for the following questions. They are not issues in a sense of bugs or feature requests (at least if you do not consider improving the readme as a FR), but I do not see any reference labeled "support" or similar, so I post it here.

Many parts of the readme seem greatly written to me, for example that you specify all the objects that are considered as "of interest" and the large section about Splunk-integration. However there are some basic background information that are not clear to me:

- Does a single DC (that does not replicate anything anywhere) also have the replication metadata? (I read https://www.ssi.gouv.fr/uploads/2019/04/ad_timeline_first_tc.pdf which says "For each replicated attribute msDS-ReplAttributeMetaData contains", but I am not sure whether "replicated attribute" means only if it *IS* replicated or also if it *would be* replicated, if a second DC would exist)

- Does Windows server keep the replication metadata indefinitely or will they be purged at some time similar to event logs?

- Does ADTimeline only consider the replication metadata or does it also consider the objects themselves? ("normal" metadata and other fields)? Reading the readme feels like this tool is only about replication metadata, on the other hand it is called ADTimeline, not ADRepDataTimeline or similar.

Thank you very much.

**Comment by ldap389** [comment]
- A single DC has replication metadata. In case a second DC is added later on.
- It is never purged, but you have only the last modification of each replicated attribute. 
- The timeline itself (CSV file) is only build with replication metadata. But the objects attribute values are dumped aside in an XML file.

**Comment by rwiesbach** [comment]
Excellent response time again, thank you!

**Comment by ldap389** [comment]
You are welcome
