### ISSUE TITLE
Adding CustomGroups Parameter

### ISSUE THREAD

**Issue by LxLeChat** [ANSSI-FR/ADTimeline#3]
Instead of forcing the user to edit the script, consider adding a "CustomGroups" parameter.

Can be easily implemented
`[parameter(Mandatory=$false)][string[]]$CustomGroups = $null`

**Comment by ldap389** [comment]
Yes sounds a good idea. 
I was thinking instead put a filename as parameter. The user will input the custom groups in that file (one per line) and its content will be processed by the script.
What is your opinion about this? Or you would prefer stick to a comma separated string as parameter?

**Comment by LxLeChat** [comment]
I think the comma separated string as a parameter is the best solution.
Groups in a file can then be imported via the `get-content` cmdlet and passed to the parameter.

Direct input
`.\ADTimeLine.ps1 -server serverx -CustomGroups group1,group2`

Via File
```
$customgroups = get-content c:\temp\customgroups.txt
.\ADTimeLine.ps1 -server serverx -CustomGroups $CustomGroups
```

Is this ok with you ?

**Comment by ldap389** [comment]
Custom group as parameter feature pushed in last commit
