### ISSUE TITLE
Error Handling logic

### ISSUE THREAD

**Issue by LxLeChat** [ANSSI-FR/ADTimeline#4]
Consider using try/catch logic for error handling.
Instead of checking if $error exists, and clearing it, maybe you could use some try catch logic.

For Example:
```
# LDAP root information, to retrieve partitions paths
$root = Get-ADRootDSE -server $server

if($error)
	{
	write-output -inputobject "---- Connexion au DC $($server) impossible ----"
	Exit $ERR_GC_BIND_FAILED
	}

```
Try the following:
```
# LDAP root information, to retrieve partitions paths
Try {
    $root = Get-ADRootDSE -server $server
} Catch {
    #You Can directly explore the current error by using $_ or $PSItem
    write-output -inputobject "---- Connexion au DC $($server) impossible ----"
	Exit $ERR_GC_BIND_FAILED
}
```

**Comment by ldap389** [comment]
The "try catch" error handling is not pratictal in some parts of my script: For example when I am appending eventual errors inside a loop by not clearing the $error variable, and processing then cleaning it when the loop is exited.
For coherence purpose I sticked to the same logic everywhere in the script.
This "Try catch" thing is more a coding style issue, the method I use for handling erros does not decrease performance nor induce some processing errors.
For those reasons I am closing the issue.
