### ISSUE TITLE
Alternate way to resolve current site name

### ISSUE THREAD

**Issue by LxLeChat** [ANSSI-FR/ADTimeline#6]
Instead of using nltest:
`$mySite = (nltest /dsgetsite 2>$null)[0]`

you can use the following to retrieve the current site name:
`[System.DirectoryServices.ActiveDirectory.ActiveDirectorySite]::GetComputerSite().Name`

Could this be ok?

**Comment by ldap389** [comment]
Yes this will work in 99,9% of the cases. The original code used to retrieve the site name this way. But in some very rare cases the call via 
_System.DirectoryServices.ActiveDirectory.ActiveDirectorySite_ returned an error whereas the good old nltest command line worked fine.
That is why this less elegant option was choosen.
