### ISSUE TITLE
Question why not use admon

### ISSUE THREAD

**Issue by ryanfaircloth** [ANSSI-FR/ADTimeline#7]
On first glance, it looks like the timeline script collects similar fields to admon which is already commonly deployed. Could admon be used instead of the new script which would commonly be resisted by customers for non technical reasons?

**Comment by ldap389** [comment]
Admon uses [LDAP change notification](https://docs.microsoft.com/en-us/windows/win32/ad/change-notifications-in-active-directory-domain-services) to monitor in real time AD changes.

The aim of the ADtimeline tool is to use replication metadata to get changes that already occurred: It is a forensic tool, not a monitoring tool. Replication metadata and deleted objects is not collected with Admon. 

In addition the timeline generated with the ADTimeline PowerShell script could be analyzed by a DFIR analyst not only with Splunk.
