### ISSUE TITLE
Running with Splunk

### ISSUE THREAD

**Issue by wkleinhenz** [ANSSI-FR/ADTimeline#8]
ive installed the app in splunk and was wondering if it would be possible and/or a good idea to use the script input in splunk to run the discovery script on a schedule tp collect data

**Comment by ldap389** [comment]
Hello,

This is not impossible but you might not want to index twice the same data. As a consequence you would need to index only the diff between two adobjects.xml and adtimeline.csv collected via scheduled task.
ADTimeline is a forensics tool and not a monitoring tool.
I suggest you use dedicated apps if you wish to monitor AD changes with Splunk. [The ADmon app](https://www.splunk.com/en_us/blog/tips-and-tricks/working-with-active-directory-on-splunk-universal-forwarders.html) might fit your needs.
I hope this answers your question.

**Comment by wkleinhenz** [comment]
thanks that makes sense
